New console frontend: Add support for network event message
firefox-devtools/original-console-fork pull request #262
Opened 2016-09-08 09:20 UTC by rickychien

Fixes #195 

## Support for network event message
- [x] Method
- [x] XHR
- [x] URL
- [x] click URL and link to Network Panel
- [x] Partial support for network status (it will be fully supported in NetworkUpdateMessage)
- [x] Mixed content (Test website: https://people.mozilla.org/~tvyas/mixedboth.html)
- [x] Learn more link for [Mixed content]
- [x] click Learn more link for [Mixed content] and link to Network Panel

2016-09-08 16:28 UTC, linclark commented on devtools/client/themes/webconsole.css
> -  white-space: pre-wrap;
We want to be careful about changes to the CSS in this file. This gets applied to the old console as well.

You should be able to add overrides to the [NEW CONSOLE OUTPUT section](https://github.com/rickychien/gecko-dev/blob/6dca0053274293fdfdceaf80a7ec69f75b2e9128/devtools/client/themes/webconsole.css#L672), and scope them using one of the new-console specific classes for now.

2016-09-08 16:35 UTC, linclark commented
I just downloaded this and tested it out. It looks really good!

I'm going to do another pass through the code tomorrow morning, so I will likely have more specific comments. But I think this is basically doing everything right.

2016-09-08 16:37 UTC, linclark commented
@rickychien One thing that we will need for this is tests. You will probably need to add another stub generator in order to get the necessary stubs. That can be challenging, so let me know if you run into any problems with that.

2016-09-09 02:02 UTC, rickychien commented on devtools/client/themes/webconsole.css
> -  white-space: pre-wrap;
I'll move this part into NEW CONSOLE OUTPUT section. BTW, I don't know why ```white-space: pre-wrap;``` [1] doesn't seem to take effect to render a space after method. Thus, I use this workaround to produce a space for new UI and it seems to work great.

[1] https://github.com/devtools-html/gecko-dev/blob/a09e19c97e761b4cf69be92e9ebc40cd6aa8be4d/devtools/client/themes/webconsole.css#L143

2016-09-09 11:05 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +    evt.preventDefault();
This `preventDefault` is required because we're using the `a` tag for the URLs, right? We can probably just change the `a` to a `span` instead. In the current console, it doesn't seem like you can click on the link to navigate to the URL anyway, so there's no reason that I can see for it being an `a` tag. @bgrins, what do you think?

2016-09-09 11:07 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +      dom.a({ className: "url", href: url, title: url, onClick: onUrlClick },
We probably want to reuse the URL formatting code from Reps here.

2016-09-09 11:23 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  if (httpVersion && status && statusText && totalTime) {
I tested this with Twitter and the status info wasn't showing up for me.

2016-09-09 11:26 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  let Xhr = l10n.getStr("webConsoleXhrIndicator");
`Xhr` should be `xhr` here. We capitalize when it's a React element, but not other variables for the most part.

2016-09-09 12:15 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  const isMixedContent = WebConsoleUtils.isMixedHTTPSRequest(url, currentLocation);
I tried testing this with [an example](https://googlesamples.github.io/web-fundamentals/samples/fundamentals/security/prevent-mixed-content/simple-example.html) and it didn't work for me. It shows a warning, but not a learn more link.

I also think there will be a bug in this logic. The `currentLocation` is updated every time the tab is navigated. However, the `url` for this particular message stays the same. If messages are persisted across different tab navigations, then this could return true when the message first comes in, and then return false if the user navigates to a different tab.

Let's move the code related to mixed content handling to a separate PR. Then we can land this and work that out separately.

2016-09-09 20:21 UTC, bgrins commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +    evt.preventDefault();
It's OK to go away from an <a> tag if we do a <span> with tabindex of 0: https://bugzilla.mozilla.org/show_bug.cgi?id=987373#c39.  If it will require re-styling things we might consider waiting, but I'd be fine with making the change now

2016-09-12 02:50 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +    evt.preventDefault();
Can we keep ```a``` tag here but remove its ```href```? It seems to work for me after removing ```evt.preventDefault()```

2016-09-12 03:05 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  if (httpVersion && status && statusText && totalTime) {
I prefer to leave a TODO comment on top of it to explain that feature will be finished in NetworkUpdateEvent since these properties won't arrive at the first time so that status info doesn't show up at the present.

2016-09-12 03:27 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +      dom.a({ className: "url", href: url, title: url, onClick: onUrlClick },
I suspect that you suggested me to use ```getURLDisplayString()``` in rep-utils.js which already used in object-with-url.js

2016-09-12 03:28 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  let Xhr = l10n.getStr("webConsoleXhrIndicator");
done

2016-09-12 03:44 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  const isMixedContent = WebConsoleUtils.isMixedHTTPSRequest(url, currentLocation);
Yes, it seems a bug in mixed content and your example doesn't work even in old web console.

2016-09-12 18:05 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +    evt.preventDefault();
@bgrins the thing is, I don't think that we actually do want a tabindex if clicking on it does nothing... do we? In the current console, clicking on the link doesn't take you there, AFAICT.

@rickychien I don't think the styling matters too much. I believe the only styling that we might want is the underline, but I'm fine with leaving that out for now. If clicking on the link doesn't do anything, then a hover state is confusing anyway.

2016-09-12 18:06 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +      dom.a({ className: "url", href: url, title: url, onClick: onUrlClick },
That sounds right :)

2016-09-12 18:08 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +  if (httpVersion && status && statusText && totalTime) {
I usually don't like to commit something that isn't fully working yet, but since we plan to work on that issue right after this one a TODO makes sense.

2016-09-13 06:09 UTC, rickychien commented on devtools/client/themes/webconsole.css
> -  white-space: pre-wrap;
```white-space: pre-wrap;``` works because we append a whitespace after method string in old webconsole. I'll remove this part and set a whitespace as it is.

https://github.com/devtools-html/gecko-dev/blob/a09e19c97e761b4cf69be92e9ebc40cd6aa8be4d/devtools/client/webconsole/webconsole.js#L1614

2016-09-13 09:15 UTC, rickychien commented
@linclark 
Do you think it makes sense to ```simulate("click")``` to test for a url clicking? Since behavior of url clicking is pretty simple and I'm not sure what things we're able to ensure for this.

2016-09-13 18:26 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/fixtures/stubs/networkEvent.js
> +stubPreparedMessages.set("undefined", new NetworkEventMessage({
It looks like it's generating a stub with the key `undefined` here. This probably means the event listener is getting two packets but only has one key.

2016-09-13 18:28 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/components/network-event.test.js
> +const currentLocation = "http://test.com";
We talked about this a little [before](https://github.com/devtools-html/gecko-dev/pull/262#discussion_r78169652), but we should get rid of all of the code around `currentLocation` in this PR. That can be handled in #265

2016-09-13 18:35 UTC, linclark commented on devtools/client/webconsole/new-console-output/types.js
> +  source: null,
source, type, and level could be hardcoded here.

2016-09-13 18:38 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/components/network-event.test.js
> +      expect(wrapper.find(".message-body .url").text()).toMatch(/http(s)?:\/\/.+/);
We should probably hardcode the value that we expect here. We want to make sure that it is formatting the URL as expected.

2016-09-13 18:39 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/components/network-event.test.js
> +      expect(wrapper.find(".message-body .url").text()).toMatch(/http(s)?:\/\/.+/);
Same as above.

2016-09-13 18:39 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/components/network-event.test.js
> +      expect(wrapper.find(".message-body .url").text()).toMatch(/http(s)?:\/\/.+/);
Same as above.

2016-09-13 18:40 UTC, linclark commented
@rickychien It's so awesome to see the test in here! Thanks for taking care of all that.

A few minor issues, but once those are resolved I think this is ready. Once it's in, we can start on #196... would you be interested in taking on that issue?

2016-09-13 18:43 UTC, linclark commented
> Do you think it makes sense to simulate("click") to test for a url clicking? Since behavior of url clicking is pretty simple and I'm not sure what things we're able to ensure for this.

You're right, we probably can't ensure much for this in the unit tests. I'll create an issue to make sure that we have an end-to-end test for it.

2016-09-14 02:26 UTC, rickychien commented on devtools/client/webconsole/new-console-output/test/components/network-event.test.js
> +const currentLocation = "http://test.com";
done

2016-09-14 07:26 UTC, rickychien commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +        getURLDisplayString(url)),
@linclark 
Could you check the display url on webconsole? I followed you suggestion to use this API from reps and url string is limited by 50 characters. It looks weird to me.

2016-09-14 15:29 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/message-types/network-event-message.js
> +        getURLDisplayString(url)),
Ah, yeah. I'd say just keep it like you had it then.

2016-09-14 15:31 UTC, linclark commented on devtools/client/webconsole/new-console-output/actions/ui.js
> +  LOCATION_CHANGE,
We should remove all of the location change code, including this and the other related code.

2016-09-15 04:01 UTC, rickychien commented
New pull request review looks pretty cool!

@linclark Last issues has been addressed and I can't wait to see your PR approval.

2016-09-15 14:48 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/console-output.js
> +const { getAllUi } = require("devtools/client/webconsole/new-console-output/selectors/ui");
I believe this should have been removed when the currentLocation code was removed. This component is no longer using anything from the UI selector.

When we do implement the location stuff, the UI reducer/selector is probably not the best place for it. Instead, I'm thinking we'll probably want to create a part of the state tree that is just in charge of backend state.

2016-09-15 14:48 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/console-output.js
> +    ui: PropTypes.object.isRequired,
Same as above.

2016-09-15 14:50 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/console-output.js
> +      ui,
Same as above.

2016-09-15 14:50 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/console-output.js
> +    ui: getAllUi(state),
Same as above.

2016-09-15 14:52 UTC, linclark commented on devtools/client/webconsole/new-console-output/new-console-output-wrapper.js
> +const uiActions = require("devtools/client/webconsole/new-console-output/actions/ui");
Same as above (regarding UI selectors/reducers).

2016-09-15 14:52 UTC, linclark commented on devtools/client/webconsole/new-console-output/new-console-output-wrapper.js
> +const messageActions = require("devtools/client/webconsole/new-console-output/actions/messages");
Message actions can be renamed to actions again.

2016-09-15 14:54 UTC, linclark commented on devtools/client/webconsole/new-console-output/utils/messages.js
> +        source: MESSAGE_SOURCE.NETWORK,
When I said these could be hardcoded, I meant you could move them to the definition of `NetworkEventMessage` in `types.js`.

2016-09-15 14:59 UTC, linclark requested changes
Unfortunately there are still a few outstanding changes from the previous reviews. Once those are cleared up, this will be ready.

2016-09-15 14:59 UTC, linclark commented
@rickychien agreed, the new review system is awesome!

2016-09-15 15:56 UTC, rickychien commented
Issues addressed again. @linclark thanks for your carefully review.

2016-09-15 16:06 UTC, linclark approved these changes

2016-09-15 16:07 UTC, linclark commented
This looks great. Thanks so much for taking the time on it.

2016-09-15 16:07 UTC, merged