Bug 1302873 - New console frontend: Remove quotes around strings. r=b…
firefox-devtools/original-console-fork pull request #276
Opened 2016-09-14 22:03 UTC by linclark

Fixes #275 

## Testing instructions
1. `console.log("foo", "bar")`
2. `console.log({}, {})`

@bgrins this is ready for review

2016-09-15 00:46 UTC, nchevobbe commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
we should check if `grip === "longString"` too.

2016-09-15 00:49 UTC, nchevobbe requested changes

2016-09-15 15:18 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
True. We can address that once we have a longString Rep to handle that case. I'll add a todo.

2016-09-15 18:31 UTC, linclark commented
@nchevobbe if you want to review this, I can make the name switch in the commit message

2016-09-15 20:26 UTC, nchevobbe commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
I'm unsure about this change, because we are doing the same work that occurs in the rep.js's `getRep` function.
Would it be bad to always use a Rep, and pass it the useQuotes props  ? : 

```javascript
  Rep({
    object: grip,
    objectLink: VariablesViewLink,
    defaultRep: Grip,
    useQUotes: false
  })
```

Or if you still prefer to use the StringRep here, maybe we can use the string.js's `supportsObjectsupportsObject` function ? So we make sure to handle future cases.

2016-09-15 20:48 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
Right now, [Rep does not explicitly support the `useQuotes` prop](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/reps/rep.js#72). We could easily change that. However, I'm not sure that we want to.

Our use case is kind of complicated. We don't want to have `useQuotes: false` for strings at all levels. We only want it if the string is at the top level.

If we were to use `Rep` here, it would probably work how we want it to. But it would work more because of happenstance than design. It would work because `Rep` [passes the whole `this.props` object](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/reps/rep.js#80) down to whatever rep it finds, but then collection reps like array are [more specific](https://dxr.mozilla.org/mozilla-central/source/devtools/client/shared/components/reps/array.js#172) in the properties they pass.

That said, if there was a change to Reps and it did break, our tests would notify us right away... and it would be easy to go back to this solution at that point.

So I'm on the fence. Given that info, what do you think?

also, @janodvarko Any thoughts? If we change this, it would mean `useQuotes` becomes an optional property of `Rep`. It would also mean that any collection object (like `grip`, `object`, `array`, and `grip-array`) would have to not pass that prop down to their child reps.

2016-09-15 22:29 UTC, nchevobbe commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
> Right now, Rep does not explicitly support the useQuotes prop. We could easily change that. However, I'm not sure that we want to.

Yeah, I don't think so too.

> So I'm on the fence. Given that info, what do you think?

You are making good points. How do you feel about using `StringRep.supportsObject` instead of directly checking the type ?

2016-09-16 17:06 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
That's a good thought. There's just one concern: `supportsObject` is designed to be used in a pattern called chain of command. That pattern basically makes it possible to construct an extensible switch statement, where you can define the branches of the switch statement across a bunch of different modules. Multiple modules' `supportsObject` function could return `true`, but it's the first one in the chain that wins.

2016-09-16 17:21 UTC, nchevobbe commented on devtools/client/webconsole/new-console-output/components/grip-message-body.js
> +    typeof grip === "string"
Okay, this way works fine for me too.

2016-09-16 17:21 UTC, nchevobbe approved these changes
:shipit:

2016-09-16 19:30 UTC, linclark commented
Thanks :) And thanks for raising those concerns. They are good to have on the radar, and I'm hoping we'll come up with a better way to handle it over time.

2016-09-16 19:35 UTC, merged