Sync prefs back to system
firefox-devtools/original-console-fork pull request #319
Opened 2016-09-27 20:35 UTC by linclark

Fixes #127 

@bgrins this is ready for review. I was working on top of inbound, but I don't think that should have an impact.

## Testing instructions
Take a look at the mochitest for a manual testing script

2016-09-27 21:47 UTC, bgrins commented on devtools/client/webconsole/new-console-output/actions/filters.js
> +      Services.prefs.setBoolPref(PREFS.FILTER[filter.toUpperCase()],
This should likely call `Services.prefs.clearUserPref(PREFS.FILTER[filter.toUpperCase()])` instead of setting it (so that it's not a user-set value but rather goes back to default).

2016-09-27 21:51 UTC, bgrins commented on devtools/client/webconsole/new-console-output/reducers/filters.js
> +  net: true,
Are these meant to be default values?  Both net and netxhr are going to be false by default, so if that's the case then it should be fetching values from pref system

2016-09-27 21:51 UTC, linclark commented on devtools/client/webconsole/new-console-output/actions/filters.js
> +      Services.prefs.setBoolPref(PREFS.FILTER[filter.toUpperCase()],
Ah, was not aware that was a thing. Will fix.

2016-09-27 21:54 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
I'd prefer to see this in a second `add_task` so that we don't need to do the outputNode1 / outputNode2 and filterBar1 / filterBar2 naming.  You can just register a second task like:

    add_task(function* () {
      // first
    });
    add_task(function* () {
      // second
    });

And the second will run once the first finishes

2016-09-27 21:55 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  EventUtils.sendMouseEvent({type: "click"},
Minor nit: I've generally switched from using EventUtils for clicks and just do this instead: `toolbar1.querySelector(".devtools-filter-icon").click()`

2016-09-27 21:55 UTC, linclark commented on devtools/client/webconsole/new-console-output/reducers/filters.js
> +  net: true,
The values are fetched from the pref system in `store.js`. I'd be open to discussion, but I prefer passing in those values as part of `initialState`.

We could change these to null if that would be preferable.

2016-09-27 21:56 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  EventUtils.sendMouseEvent({type: "click"}, filterBar1.querySelector(".error"));
Ditto

2016-09-27 21:56 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
Is it part of `add_task`'s contract that prefs will be persisted between calls?

2016-09-27 21:57 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  EventUtils.sendMouseEvent({type: "click"},
👍

2016-09-27 21:58 UTC, bgrins commented on devtools/client/webconsole/new-console-output/actions/filters.js
> +    Services.prefs.setBoolPref(PREFS.FILTER[filter.toUpperCase()],
Curious, why does the pref setting happen here in the action?  It seems that the reducers will already know exactly what the final state will be (both for the filter state and also for the ui state later)

2016-09-27 22:00 UTC, bgrins commented on devtools/client/webconsole/new-console-output/reducers/filters.js
> +  net: true,
My reading of `case constants.FILTERS_CLEAR:` on line 28/29 here is that a FILTERS_CLEAR action will end up with the wrong state (true for net and netxhr)

2016-09-27 22:00 UTC, bgrins requested changes
Generally looks good, but a few notes before this is ready to land

2016-09-27 22:01 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
Yes, they all run inside the same process and don't modify any state between the tasks.  Just a way to split up the test into multiple units

2016-09-27 22:03 UTC, linclark commented on devtools/client/webconsole/new-console-output/actions/filters.js
> +    Services.prefs.setBoolPref(PREFS.FILTER[filter.toUpperCase()],
Reducers are never supposed to have side effects.

2016-09-27 22:06 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
Just looked up the add_task docs. Since the `add_task` docs talk a lot about async, and many testing tools assume that tests are independent of each other, I'd rather not introduce dependencies between two `add_tasks`.

But you make a good point about the var names. One potential fix for this would be block scoping. I could wrap the first part in a block and then the second part in another block.

2016-09-27 22:12 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
Many mochitests use tasks as a way to split the test up into functions / 'steps' and often rely on side effects between them like prefs.  So I don't think the mochitest harness will ever be in a position to run tasks in independent processes, etc.  That said, another pattern is this:

    add_task(function* () {
      let hud1 = yield openNewTabAndConsole(TEST_URI);
      runThing1(hud1);
      yield closeToolbox();

      let hud2 = yield openNewTabAndConsole(TEST_URI);
      runThing2(hud2);
    });

Then runThing1 and runThing2 can do their own variable scoping and it makes each function more direct

2016-09-27 22:14 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  yield closeToolbox;
This should be probably be a call to `closeTabAndToolbox()`:

    yield closeTabAndToolbox()

2016-09-28 21:43 UTC, linclark commented on devtools/client/webconsole/new-console-output/reducers/filters.js
> +  net: true,
<del>With the change to use `clearUserPref`, I don't think that's an issue.</del> Sorry, was looking at the wrong file. I'm going to set those to false for now. I think it might be fine just to keep them in sync.

2016-09-28 21:43 UTC, linclark commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  // Check that the ui settings were persisted.
👍 I like this solution.

2016-09-28 22:01 UTC, linclark commented
@bgrins I think I addressed everything. Mind giving it another look?

2016-09-29 02:35 UTC, bgrins commented on devtools/client/webconsole/new-console-output/components/filter-button.js
> +      filterKey,
Is this class used anywhere?  I don't see any other reference to it

2016-09-29 02:37 UTC, bgrins commented on devtools/client/webconsole/new-console-output/store.js
> +      filterBarVisible: Services.prefs.getBoolPref("devtools.webconsole.ui.filterbar"),
This should use the PREFS.UI.FILTERBAR const

2016-09-29 02:39 UTC, bgrins commented on devtools/client/webconsole/new-console-output/test/mochitest/browser_webconsole_filters.js
> +  info("Toolbar found");
May as well convert this to an `ok(toolbar, ...)` to match the assertion on filterBar below

2016-09-29 02:42 UTC, bgrins commented
Testing this locally, I don't see the filtered message (+ the filter clear button) in the UI when the filters are causing some messages to disappear.  Is this a regression here, or am I missing it?

2016-09-29 03:10 UTC, bgrins commented
Generally this looks OK if you are aware of the issue with the clear button / if that's an existing bug.  I wasn't able to test the clear behavior because of it.

2016-09-29 10:43 UTC, linclark commented
Yes, I should have reminded you of the history on that. The `filterClear` action was added in the original filtering bar PR, but we decided to turn off that part of the UI because it wasn't returning the right number of messages.

2016-09-29 10:44 UTC, linclark commented on devtools/client/webconsole/new-console-output/components/filter-button.js
> +      filterKey,
it's used in the tests

2016-09-29 11:44 UTC, merged